In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
(x, y), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
x.shape, y.shape

((60000, 28, 28), (60000,))

In [4]:
# since x is numpy format, directly use .max, .min...
x.min(), x.max(), x.mean()

(0, 255, 33.318421449829934)

In [5]:
y[:4]

array([5, 0, 4, 1], dtype=uint8)

In [6]:
y_onehot = tf.one_hot(y, depth=10)

In [7]:
y_onehot[:2]

<tf.Tensor: id=8, shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
(x, y), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [9]:
x.shape, y.shape, x_test.shape, y_test.shape

((50000, 32, 32, 3), (50000, 1), (10000, 32, 32, 3), (10000, 1))

In [10]:
# maybe needs squeeze later...
y[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [11]:
######################################################## tf.data.Datatset ###################################################################

In [12]:
db = tf.data.Dataset.from_tensor_slices(x_test)

In [13]:
next(iter(db)).shape

TensorShape([32, 32, 3])

In [14]:
db = tf.data.Dataset.from_tensor_slices((x_test, y_test))

In [15]:
next(iter(db))[1].shape

TensorShape([1])

In [16]:
db = tf.data.Dataset.from_tensor_slices((x_test, y_test))
db = db.shuffle(10000)

In [17]:
#################################################### .map ##########################################################################

In [18]:
def preprocess(x, y):
    x = tf.cast(x, dtype=tf.float32) / 255
    y = tf.squeeze(y)
    y = tf.cast(y, dtype=tf.int32)
    y = tf.one_hot(y, depth=10)
    return x, y
db2 = db.map(preprocess)

In [19]:
res = next(iter(db2))

In [20]:
res[1].shape

TensorShape([10])

In [21]:
res[1][:2]

<tf.Tensor: id=61, shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>

In [22]:
db3 = db2.batch(32)

In [23]:
res = next(iter(db3))

In [26]:
res[0].shape

TensorShape([32, 32, 32, 3])