In [1]:
import tensorflow as tf

In [2]:
a = tf.fill([2, 2], 2.)
b = tf.ones([2, 2])

In [3]:
a + b

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [4]:
a // b , a % b

(<tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=9, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [5]:
a

<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [6]:
tf.math.log(a)

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [7]:
tf.exp(a)

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[7.389056, 7.389056],
       [7.389056, 7.389056]], dtype=float32)>

In [8]:
tf.math.log(8.) / tf.math.log(2.)

<tf.Tensor: id=21, shape=(), dtype=float32, numpy=3.0>

In [9]:
a

<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [10]:
tf.pow(a, 3)

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [11]:
a ** 3

<tf.Tensor: id=28, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [12]:
tf.sqrt(a)

<tf.Tensor: id=30, shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

In [16]:
c = tf.ones([2, 3])
d = tf.fill([3, 4], 2.)
# this equals to a@b
tf.matmul(c, d)

<tf.Tensor: id=48, shape=(2, 4), dtype=float32, numpy=
array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]], dtype=float32)>

In [14]:
a = tf.ones([4, 2, 3])
b = tf.fill([4, 3, 5], 2.)

In [15]:
a@b

<tf.Tensor: id=40, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>