In [1]:
import tensorflow as tf

In [2]:
a = tf.reshape(tf.range(9), [3, -1])

In [3]:
a.shape

TensorShape([3, 3])

In [4]:
# no padding 
tf.pad(a, [[0, 0], [0, 0]])

<tf.Tensor: id=7, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [5]:
tf.pad(a, [[1, 0], [0, 0]])

<tf.Tensor: id=10, shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [6]:
a = tf.random.normal([4, 28, 28, 3])
b = tf.pad(a, [[0, 0], [2, 2], [2, 2], [0, 0]])
b.shape

TensorShape([4, 32, 32, 3])

In [7]:
a.shape

TensorShape([4, 28, 28, 3])

In [11]:
a = tf.reshape(tf.range(9), [-1, 3])

In [12]:
a.shape

TensorShape([3, 3])

In [14]:
# 把第二个维度扩散为原来的2倍
tf.tile(a, [1, 2])

<tf.Tensor: id=34, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

In [19]:
aa = tf.expand_dims(a, axis=1)

In [20]:
aa.shape

TensorShape([3, 1, 3])

In [22]:
tf.broadcast_to(aa, [3, 2, 3])

<tf.Tensor: id=44, shape=(3, 2, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [0, 1, 2]],

       [[3, 4, 5],
        [3, 4, 5]],

       [[6, 7, 8],
        [6, 7, 8]]])>