In [1]:
import tensorflow as tf

In [2]:
################################################### sort, argsort ###################################################################

In [3]:
a = tf.random.shuffle(tf.range(5))

In [4]:
a

<tf.Tensor: id=4, shape=(5,), dtype=int32, numpy=array([2, 0, 3, 1, 4])>

In [5]:
# can also set direction to ASCENDING, and ASCENDING is default
tf.sort(a, direction='DESCENDING')

<tf.Tensor: id=14, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [6]:
tf.argsort(a, direction='DESCENDING')

<tf.Tensor: id=26, shape=(5,), dtype=int32, numpy=array([4, 2, 0, 3, 1])>

In [7]:
idx = tf.argsort(a, direction='DESCENDING')
tf.gather(a, idx)

<tf.Tensor: id=39, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [8]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)

In [9]:
a

<tf.Tensor: id=44, shape=(3, 3), dtype=int32, numpy=
array([[5, 0, 6],
       [9, 3, 7],
       [5, 5, 6]])>

In [10]:
tf.sort(a)

<tf.Tensor: id=57, shape=(3, 3), dtype=int32, numpy=
array([[0, 5, 6],
       [3, 7, 9],
       [5, 5, 6]])>

In [11]:
tf.argsort(a)

<tf.Tensor: id=69, shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [1, 2, 0],
       [0, 1, 2]])>

In [12]:
########################################### top_k ##############################################################################

In [13]:
a

<tf.Tensor: id=44, shape=(3, 3), dtype=int32, numpy=
array([[5, 0, 6],
       [9, 3, 7],
       [5, 5, 6]])>

In [14]:
# returns a tuple
res = tf.math.top_k(a, 2)

In [15]:
res.indices

<tf.Tensor: id=74, shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [0, 2],
       [2, 0]])>

In [16]:
res.values

<tf.Tensor: id=73, shape=(3, 2), dtype=int32, numpy=
array([[6, 5],
       [9, 7],
       [6, 5]])>

In [17]:
##################################################### top-k accuracy #######################################################################

In [18]:
prob = tf.constant([[0.1, 0.2, 0.7], [0.2, 0.7, 0.1]])
target = tf.constant([2, 0])

In [19]:
k_b = tf.math.top_k(prob, 3).indices

In [20]:
k_b

<tf.Tensor: id=81, shape=(2, 3), dtype=int32, numpy=
array([[2, 1, 0],
       [1, 0, 2]])>

In [21]:
k_b = tf.transpose(k_b)

In [22]:
# 现在第一行是top1的预测值，第二行是top2的预测值，第三行是top3的预测值
k_b

<tf.Tensor: id=84, shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 0],
       [0, 2]])>

In [23]:
target = tf.broadcast_to(target, [3, 2])

In [24]:
a = (1, 5, 3)
max(a)

5

In [25]:
a = tf.constant([[1, 2], [3, 4]])

In [26]:
a

<tf.Tensor: id=88, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [27]:
a[:1]

<tf.Tensor: id=93, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [34]:
tf.reshape(a[:2], [-1])

<tf.Tensor: id=131, shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>