In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: id=0, shape=(), dtype=float64, numpy=2.0>

In [3]:
a = tf.range(5)

In [4]:
a.numpy()

array([0, 1, 2, 3, 4])

In [5]:
a.ndim

1

In [6]:
a.shape

TensorShape([5])

In [7]:
a.numpy().shape

(5,)

In [8]:
# the same as a.ndim but the return type is different
tf.rank(a)

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=1>

In [9]:
tf.is_tensor(a)

True

In [10]:
a.dtype

tf.int32

In [11]:
a.dtype == tf.int32

True

In [12]:
b = np.arange(5)

In [13]:
a.dtype

tf.int32

In [14]:
aa = tf.convert_to_tensor(a)

In [15]:
aa

<tf.Tensor: id=5, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [16]:
# is equal to aa = tf.convert_to_tensor(a, dtype=tf.in64)
aa = tf.cast(aa, dtype=tf.int64)

In [17]:
aa = tf.cast(aa, dtype=tf.double)

In [18]:
aa

<tf.Tensor: id=12, shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [19]:
########################################### Variable #################################################

In [20]:
# a variable is trainable
b = tf.Variable(a)

In [21]:
b

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [22]:
b.trainable

True

In [23]:
b.dtype

tf.int32

In [24]:
c = tf.ones([])

In [25]:
c

<tf.Tensor: id=23, shape=(), dtype=float32, numpy=1.0>

In [26]:
c.numpy()

1.0

In [27]:
int(c)

1

In [28]:
############################################### Create Tensor ########################################################

In [29]:
# *** from Numpy, List ***

In [30]:
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=27, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [31]:
tf.convert_to_tensor([[2.], [1.]])

<tf.Tensor: id=29, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [1.]], dtype=float32)>

In [32]:
# *** tf.zeros ***

In [33]:
tf.zeros([])

<tf.Tensor: id=31, shape=(), dtype=float32, numpy=0.0>

In [34]:
tf.zeros([1])

<tf.Tensor: id=35, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [35]:
# [2, 2] is shape not the real data
tf.zeros([2, 2])

<tf.Tensor: id=39, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [36]:
# *************************************************** tf.zeros_like **********************************************************

In [37]:
a = tf.zeros([2, 3])
# equal to tf.zeros(a.shape)
b = tf.zeros_like(a)
b

<tf.Tensor: id=44, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [38]:
# *** tf.ones , tf.ones_like *** 

In [39]:
# refer to tf.zeros, tf.zeros_like

In [40]:
# ************************************************************* fill *********************************************************

In [41]:
tf.fill([2, 2], 1)

<tf.Tensor: id=48, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [42]:
tf.fill([2, 3], 3)

<tf.Tensor: id=52, shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]])>

In [43]:
# ************************************************** truncated_normal ***************************************************

In [44]:
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: id=59, shape=(2, 2), dtype=float32, numpy=
array([[0.8775947 , 0.95838237],
       [3.1222036 , 0.239191  ]], dtype=float32)>

In [45]:
tf.random.normal([2, 2])

<tf.Tensor: id=66, shape=(2, 2), dtype=float32, numpy=
array([[ 0.00985085,  0.07657491],
       [-1.3211715 , -1.0061271 ]], dtype=float32)>

In [46]:
tf.random.truncated_normal([2, 3], mean=0, stddev=1)

<tf.Tensor: id=73, shape=(2, 3), dtype=float32, numpy=
array([[-0.53487074,  0.71712977,  0.00165771],
       [-1.1005611 ,  0.48408553,  1.0747396 ]], dtype=float32)>

In [47]:
# ****************************************************** uniform ******************************************************

In [48]:
tf.random.uniform([2, 2], minval=0, maxval=10)

<tf.Tensor: id=81, shape=(2, 2), dtype=float32, numpy=
array([[9.023775 , 7.2566676],
       [7.7979126, 4.7285223]], dtype=float32)>

In [49]:
# ****************************************************** random permutation ******************************************************

In [50]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

In [51]:
idx

<tf.Tensor: id=87, shape=(10,), dtype=int32, numpy=array([7, 6, 9, 4, 1, 0, 3, 2, 8, 5])>

In [52]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

In [53]:
b

<tf.Tensor: id=98, shape=(10,), dtype=int32, numpy=array([5, 6, 7, 6, 5, 9, 1, 2, 2, 2])>

In [54]:
a = tf.gather(a, idx)
b = tf.gather(b, idx)

In [55]:
b

<tf.Tensor: id=103, shape=(10,), dtype=int32, numpy=array([2, 1, 2, 5, 6, 5, 6, 7, 2, 9])>

In [56]:
# ********************************************** tf.constant ************************************************************

In [57]:
# is actually the same as tf.convert_to_tensor

In [59]:
tf.constant([[1.], [2]])

<tf.Tensor: id=105, shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [60]:
##################################################### loss ###############################################################

In [61]:
out = tf.random.uniform([4, 10])

In [64]:
out

<tf.Tensor: id=113, shape=(4, 10), dtype=float32, numpy=
array([[0.63923526, 0.5296953 , 0.9156133 , 0.37180316, 0.0511111 ,
        0.08969736, 0.62992156, 0.49364734, 0.8771504 , 0.13809574],
       [0.11021626, 0.94811344, 0.2036686 , 0.94173825, 0.722103  ,
        0.63784444, 0.67117834, 0.6825385 , 0.7434186 , 0.61574113],
       [0.3710103 , 0.04950106, 0.20267642, 0.42573857, 0.6150527 ,
        0.48524094, 0.76684034, 0.9316255 , 0.8247477 , 0.9317937 ],
       [0.20751357, 0.54479015, 0.7569276 , 0.16376579, 0.9823866 ,
        0.03961587, 0.9210763 , 0.80507827, 0.33578515, 0.78288436]],
      dtype=float32)>

In [63]:
y = tf.range(4)
y = tf.one_hot(y, depth=10)

In [65]:
y

<tf.Tensor: id=125, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [66]:
loss = tf.keras.losses.mse(y, out)

In [67]:
loss

<tf.Tensor: id=130, shape=(4,), dtype=float32, numpy=array([0.28269237, 0.37196174, 0.45752445, 0.480093  ], dtype=float32)>

In [68]:
loss = tf.reduce_mean(loss)

In [69]:
loss

<tf.Tensor: id=133, shape=(), dtype=float32, numpy=0.3980679>

In [71]:
######################################################### Vector ###########################################################################

In [72]:
net = tf.keras.layers.Dense(10)

In [74]:
net.build((4, 8))

In [75]:
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.46874857,  0.44468403,  0.05889839, -0.24625275, -0.38573027,
         0.07878482, -0.44916922, -0.4241122 , -0.13674694,  0.47963166],
       [ 0.11065686, -0.57048655,  0.53424597, -0.27048633, -0.28576174,
        -0.5555568 ,  0.03807592, -0.49732244,  0.09583539, -0.5714303 ],
       [-0.56244844, -0.48534226,  0.3307783 , -0.1028797 , -0.22465873,
         0.08251411,  0.43645763, -0.25588307, -0.36016077, -0.36536133],
       [-0.00590855,  0.30332917, -0.52346563,  0.29325682,  0.09598875,
        -0.28771046,  0.15390086,  0.39869434, -0.29467425, -0.48946708],
       [-0.56249154,  0.480762  ,  0.34452623, -0.03832161,  0.22605646,
        -0.23509446,  0.5351589 ,  0.526989  , -0.34855014, -0.5352815 ],
       [-0.5379998 ,  0.1835227 ,  0.57323956, -0.29090825, -0.20032203,
        -0.4013461 ,  0.44645023, -0.26013207, -0.10537255,  0.060386  ],
       [ 0.5300653 ,  0.01351994,  0.05596453,  0.33855504

In [76]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [79]:
x = tf.random.normal([4, 784])
net = tf.keras.layers.Dense(10)

In [80]:
net(x).shape

TensorShape([4, 10])

In [83]:
# shape of weights
net.kernel.shape

TensorShape([784, 10])

In [84]:
net.bias.shape

TensorShape([10])

In [85]:
x =  tf.random.normal((4, 32, 32, 3))

In [89]:
net = tf.keras.layers.Conv2D(16, kernel_size=3)

In [91]:
net(x).shape

TensorShape([4, 30, 30, 16])