In [1]:
import tensorflow as tf

In [3]:
# here we have 5 boxes, each box has 4 coordinates
boxes = tf.random.uniform([5, 4], minval=0, maxval=10)

In [4]:
boxes

<tf.Tensor: id=13, shape=(5, 4), dtype=float32, numpy=
array([[4.3398676 , 7.3400345 , 1.877315  , 0.18413186],
       [0.98822236, 7.902124  , 0.8090663 , 1.2118781 ],
       [5.9656024 , 9.474609  , 9.505417  , 6.9947553 ],
       [4.6755543 , 9.095127  , 1.1614668 , 6.1340427 ],
       [1.2248063 , 8.7956295 , 5.155654  , 3.829707  ]], dtype=float32)>

In [6]:
# scores for each box
scores = tf.random.uniform([5], minval=0, maxval=1)

In [7]:
scores

<tf.Tensor: id=21, shape=(5,), dtype=float32, numpy=
array([0.63024914, 0.8778267 , 0.00629103, 0.23664343, 0.6832211 ],
      dtype=float32)>

In [10]:
# returns the indices of the boxes meet the threshold
indices = tf.image.non_max_suppression(boxes, scores, max_output_size=10, iou_threshold=0.2)
indices

<tf.Tensor: id=36, shape=(3,), dtype=int32, numpy=array([1, 4, 2])>

In [11]:
tf.gather(boxes, indices=indices)

<tf.Tensor: id=39, shape=(3, 4), dtype=float32, numpy=
array([[0.98822236, 7.902124  , 0.8090663 , 1.2118781 ],
       [1.2248063 , 8.7956295 , 5.155654  , 3.829707  ],
       [5.9656024 , 9.474609  , 9.505417  , 6.9947553 ]], dtype=float32)>