In [1]:
import tensorflow as tf 
from tensorflow import keras

In [2]:
x = tf.random.normal([4, 788])

In [3]:
net = tf.keras.layers.Dense(512)
out = net(x)  

In [4]:
out.shape

TensorShape([4, 512])

In [5]:
# shape of weights, shape of bias
net.kernel.shape, net.bias.shape

(TensorShape([788, 512]), TensorShape([512]))

In [6]:
net = tf.keras.layers.Dense(10)

In [7]:
# below will raise error, Dense object has no attribute 'bias'
# net.bias

In [8]:
# will be empty before given 
net.get_weights(), net.weights

([], [])

In [9]:
net.build(input_shape=(None, 4))

In [10]:
net.get_weights()

[array([[ 0.53446555,  0.22008818,  0.5262387 , -0.49800426,  0.4289534 ,
         -0.16301975,  0.63278663,  0.06394708,  0.22146088, -0.19235292],
        [ 0.5756086 , -0.5126367 ,  0.17382014,  0.63976204,  0.55513   ,
          0.31101757,  0.0278036 ,  0.3967663 , -0.44127184,  0.61096   ],
        [-0.19367698,  0.48155951, -0.31084415,  0.53555167, -0.45724416,
         -0.5796112 ,  0.34066164, -0.06689358, -0.31299776, -0.1051625 ],
        [ 0.6176175 , -0.42139488,  0.45368803,  0.4942336 ,  0.46620226,
         -0.18579423,  0.48498058,  0.50759244, -0.37934586,  0.14635289]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [11]:
net.kernel

<tf.Variable 'kernel:0' shape=(4, 10) dtype=float32, numpy=
array([[ 0.53446555,  0.22008818,  0.5262387 , -0.49800426,  0.4289534 ,
        -0.16301975,  0.63278663,  0.06394708,  0.22146088, -0.19235292],
       [ 0.5756086 , -0.5126367 ,  0.17382014,  0.63976204,  0.55513   ,
         0.31101757,  0.0278036 ,  0.3967663 , -0.44127184,  0.61096   ],
       [-0.19367698,  0.48155951, -0.31084415,  0.53555167, -0.45724416,
        -0.5796112 ,  0.34066164, -0.06689358, -0.31299776, -0.1051625 ],
       [ 0.6176175 , -0.42139488,  0.45368803,  0.4942336 ,  0.46620226,
        -0.18579423,  0.48498058,  0.50759244, -0.37934586,  0.14635289]],
      dtype=float32)>

In [12]:
############################################# Sequential ##############################################################################

In [13]:
x = tf.random.normal([2, 3])

In [15]:
model = keras.Sequential([
    keras.layers.Dense(2, activation='relu'), 
    keras.layers.Dense(2, activation='relu'),
    keras.layers.Dense(2)
])
model.build(input_shape=[None, 3])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              multiple                  8         
_________________________________________________________________
dense_3 (Dense)              multiple                  6         
_________________________________________________________________
dense_4 (Dense)              multiple                  6         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [16]:
for p in model.trainable_variables:
    print(p.name, p.shape)

dense_2/kernel:0 (3, 2)
dense_2/bias:0 (2,)
dense_3/kernel:0 (2, 2)
dense_3/bias:0 (2,)
dense_4/kernel:0 (2, 2)
dense_4/bias:0 (2,)


In [19]:
# sigmoid and softmax
a = tf.linspace(-2., 2, 5)
tf.sigmoid(a)

<tf.Tensor: id=168, shape=(5,), dtype=float32, numpy=
array([0.11920291, 0.26894143, 0.5       , 0.7310586 , 0.880797  ],
      dtype=float32)>

In [20]:
tf.nn.softmax(a)

<tf.Tensor: id=170, shape=(5,), dtype=float32, numpy=
array([0.01165623, 0.03168492, 0.08612854, 0.23412167, 0.6364086 ],
      dtype=float32)>

In [21]:
# more softmax examples
logits = tf.random.uniform([1, 10], minval=-2, maxval=2)
# also tf.math.softmax
prob = tf.nn.softmax(logits, axis=1)
tf.reduce_sum(prob, axis=1)

<tf.Tensor: id=181, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [22]:
# tanh

In [27]:
a = tf.cast(tf.range(-2, 2), dtype=tf.double)
a

<tf.Tensor: id=196, shape=(4,), dtype=float64, numpy=array([-2., -1.,  0.,  1.])>

In [28]:
tf.tanh(a)

<tf.Tensor: id=198, shape=(4,), dtype=float64, numpy=array([-0.96402758, -0.76159416,  0.        ,  0.76159416])>