In [1]:
import tensorflow as tf

In [5]:
a = tf.linspace(-10., 10, 10)

In [6]:
with tf.GradientTape() as tape:
    tape.watch([a])
    y = tf.sigmoid(a)
grads = tape.gradient(y, [a])

In [7]:
grads

<tf.Tensor: id=19, shape=(10,), dtype=float32, numpy=
array([4.5386874e-05, 4.1860685e-04, 3.8362255e-03, 3.3258751e-02,
       1.8632649e-01, 1.8632641e-01, 3.3258699e-02, 3.8362255e-03,
       4.1854731e-04, 4.5416677e-05], dtype=float32)>

In [10]:
a = tf.linspace(-5., 5, 10)
tf.tanh(a)

<tf.Tensor: id=32, shape=(10,), dtype=float32, numpy=
array([-0.9999092 , -0.9991625 , -0.99229795, -0.9311096 , -0.50467217,
        0.5046725 ,  0.93110967,  0.99229795,  0.9991625 ,  0.9999092 ],
      dtype=float32)>

In [11]:
# relu

In [12]:
a = tf.linspace(-1., 1, 10)
tf.nn.relu(a)

<tf.Tensor: id=38, shape=(10,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11111116, 0.33333337, 0.5555556 , 0.7777778 , 1.        ],
      dtype=float32)>

In [13]:
tf.nn.leaky_relu(a)

<tf.Tensor: id=40, shape=(10,), dtype=float32, numpy=
array([-0.2       , -0.15555556, -0.11111112, -0.06666666, -0.02222222,
        0.11111116,  0.33333337,  0.5555556 ,  0.7777778 ,  1.        ],
      dtype=float32)>