In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.random.normal([3, 3])

In [3]:
a

<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
array([[-1.1352    , -0.8478685 , -0.08308318],
       [ 0.27511054, -1.8977275 ,  0.3044168 ],
       [-0.69612366,  1.1926893 , -0.47024682]], dtype=float32)>

In [4]:
mask = a > 0

In [5]:
mask 

<tf.Tensor: id=8, shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])>

In [6]:
tf.boolean_mask(a, mask)

W0807 21:58:05.351753 24340 deprecation.py:323] From D:\work\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py:1340: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


<tf.Tensor: id=36, shape=(3,), dtype=float32, numpy=array([0.27511054, 0.3044168 , 1.1926893 ], dtype=float32)>

In [7]:
indices = tf.where(mask)
indices

<tf.Tensor: id=38, shape=(3, 2), dtype=int64, numpy=
array([[1, 0],
       [1, 2],
       [2, 1]], dtype=int64)>

In [8]:
tf.gather_nd(a, indices)

<tf.Tensor: id=40, shape=(3,), dtype=float32, numpy=array([0.27511054, 0.3044168 , 1.1926893 ], dtype=float32)>

In [9]:
mask

<tf.Tensor: id=8, shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])>

In [10]:
A = tf.ones([3, 3])

In [11]:
B = tf.zeros([3, 3])

In [12]:
tf.where(mask, A, B)

<tf.Tensor: id=49, shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 1., 0.]], dtype=float32)>

In [13]:
################################################ scatter_nd #####################################################################

In [14]:
indices = tf.constant([[4], [3], [1], [7]])

In [15]:
updates = tf.constant([9, 10, 11, 12])

In [16]:
shape = tf.constant([8])

In [17]:
shape

<tf.Tensor: id=53, shape=(1,), dtype=int32, numpy=array([8])>

In [18]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: id=55, shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12])>

In [19]:
indices = tf.constant([[0], [2]])

In [20]:
updates = tf.constant([ [[2, 2, 2, 2],
                         [2, 2, 2, 2],
                         [2, 2, 2, 2],
                         [2, 2, 2, 2]], 
                         [ [2, 2, 2, 2],
                           [2, 3, 2, 2],
                           [2, 2, 5, 2],
                           [2, 2, 2, 7] ]])

In [21]:
shape = tf.constant([4, 4, 4])

In [22]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: id=60, shape=(4, 4, 4), dtype=int32, numpy=
array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[2, 2, 2, 2],
        [2, 3, 2, 2],
        [2, 2, 5, 2],
        [2, 2, 2, 7]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])>

In [23]:
################################################ meshgrid ###############################################################################

In [24]:
points = []
for y in np.linspace(-2, 2, 5):
    for x in np.linspace(-2, 2, 5):
        points.append([x, y])
np.array([points])

array([[[-2., -2.],
        [-1., -2.],
        [ 0., -2.],
        [ 1., -2.],
        [ 2., -2.],
        [-2., -1.],
        [-1., -1.],
        [ 0., -1.],
        [ 1., -1.],
        [ 2., -1.],
        [-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.],
        [-2.,  1.],
        [-1.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.],
        [-2.,  2.],
        [-1.,  2.],
        [ 0.,  2.],
        [ 1.,  2.],
        [ 2.,  2.]]])

In [25]:
y = tf.linspace(-2., 2, 5)
x = tf.linspace(-2., 2, 5)
# points_x, points_y = tf.meshgrid(x, y)
points_x, points_y = tf.meshgrid(x, y)

In [26]:
points_x

<tf.Tensor: id=88, shape=(5, 5), dtype=float32, numpy=
array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]], dtype=float32)>

In [27]:
points_y

<tf.Tensor: id=89, shape=(5, 5), dtype=float32, numpy=
array([[-2., -2., -2., -2., -2.],
       [-1., -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.]], dtype=float32)>

In [28]:
points = tf.stack([points_x, points_y], axis=2)

In [29]:
points

<tf.Tensor: id=92, shape=(5, 5, 2), dtype=float32, numpy=
array([[[-2., -2.],
        [-1., -2.],
        [ 0., -2.],
        [ 1., -2.],
        [ 2., -2.]],

       [[-2., -1.],
        [-1., -1.],
        [ 0., -1.],
        [ 1., -1.],
        [ 2., -1.]],

       [[-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.]],

       [[-2.,  1.],
        [-1.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[-2.,  2.],
        [-1.,  2.],
        [ 0.,  2.],
        [ 1.,  2.],
        [ 2.,  2.]]], dtype=float32)>

In [ ]:
####################################################### other tests ########################################################################

In [30]:
a = np.array([1., 2.])

In [31]:
a

array([1., 2.])

In [35]:
a.astype(np.int32)

array([1, 2])

In [6]:
a = np.array([[1,2],[3,4]])

In [7]:
b = np.array([[5, 6], [7, 8]])

In [9]:
c = np.concatenate((a, b), axis = 1)

In [10]:
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [2]:
logits = tf.random.uniform([6,1])

In [3]:
logits

<tf.Tensor: id=6, shape=(6, 1), dtype=float32, numpy=
array([[0.8461815 ],
       [0.7155889 ],
       [0.03482223],
       [0.48554647],
       [0.9395963 ],
       [0.10179281]], dtype=float32)>

In [5]:
tf.ones_like(logits)

<tf.Tensor: id=14, shape=(6, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [4]:
a = np.array([[2, 3], [5, 6], [2, 6]])
b = np.array([[6, 7], [3, 5]])
a, b

(array([[2, 3],
        [5, 6],
        [2, 6]]), array([[6, 7],
        [3, 5]]))

In [5]:
(a * 2) + (b * 3)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 