In [199]:
import tensorflow as tf

In [200]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

In [201]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [202]:
for element in dataset:
    print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [203]:
for element in dataset:
    # cate tensor type to numpy type
    print(element.numpy())

1
2
3
4
5
6


In [204]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [205]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [206]:
for element in dataset:
    print(element.numpy())

[1 2]
[3 4]
[5 6]


In [207]:
dataset_dic = tf.data.Dataset.from_tensor_slices({
    'a': [1, 2],
    'b': [2, 3],
}
)

In [208]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: ()}, types: {a: tf.int32, b: tf.int32}>

In [209]:
for ele in dataset:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


In [210]:
import numpy as np

In [211]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6]))

In [212]:
for ele in dataset.take(5):
    print(ele.numpy())

1
2
3
4
5


In [213]:
# dataset.shuffle(7), only this will not work
dataset = dataset.shuffle(3)
dataset = dataset.repeat(count=3)

In [214]:
for ele in dataset:
    print(ele.numpy())

3
2
4
1
6
5
1
3
4
2
5
6
3
4
5
2
1
6


In [215]:
dataset = dataset.batch(4)

In [216]:
for ele in dataset:
    print(ele.numpy())

[3 2 4 1]
[6 5 1 3]
[4 2 5 6]
[3 4 5 2]
[1 6]


In [217]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6]))

In [218]:
dataset = dataset.map(tf.square)

In [219]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36


In [220]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([[1, 2], [3, 4], [5, 6]]))

In [221]:
# dataset = dataset.batch(2)
dataset = dataset.shuffle(3).repeat(3)

In [222]:
for e in dataset:
    print(e.numpy())

[1 2]
[5 6]
[3 4]
[1 2]
[5 6]
[3 4]
[5 6]
[1 2]
[3 4]
